### ISSUE TITLE
Retire and point to api-guidelines

### ISSUE THREAD

**Issue by kw217** [aturon/aturon.github.io#11]
A Google search for "Rust naming conventions" returns https://aturon.github.io/style/naming.html as the top hit. But this is a three-year-old snapshot; it would be much better for people to refer to https://rust-lang-nursery.github.io/api-guidelines/naming.html which is current.

Is there any chance you could retire this snapshot, or at least add pointers to more recent docs?

Thanks!

**Comment by aturon** [comment]
Done!

**Comment by kw217** [comment]
Thanks!

**Comment by thePalindrome** [comment]
Could you make that a 301 code, to help ease the transition, I know I was really confused when it suddenly gave a (rather unhelpful) 404
