### ISSUE TITLE
broken link from search engine

### ISSUE THREAD

**Issue by ghost** [aturon/aturon.github.io#13]
I can find this via search engine https://aturon.github.io/ownership/builders.html
but it's 404

**Comment by aturon** [comment]
Current API guidelines can now be found here: https://rust-lang-nursery.github.io/api-guidelines/

**Comment by ghost** [comment]
Thanks for the link! Cheers.<details><summary></summary>
92550c4de6a845ffb27a3425b63f7c40a21e3dd7
</details>

**EDIT:** what I was looking for (in the new link) is: https://rust-lang-nursery.github.io/api-guidelines/type-safety.html#c-builder
in the old link(unrendered) is: https://github.com/xftroxgpx/aturon.github.io/blob/master/ownership/builders.html
