### ISSUE TITLE
consuming vs. non-consuming builder pattern

### ISSUE THREAD

**Issue by colin-kiegel** [aturon/aturon.github.io#5]
@aturon: https://aturon.github.io/ownership/builders.html claims, that non-consuming builder pattern works with the _one-liner-pattern. I think this is wrong - the following code does not compile (copy-paste this to https://play.rust-lang.org/)

``` rust
#[derive(Debug, Default)]
struct Channel {
    special_info: i32
}

impl Channel {
    fn special_info<VALUE: Into<i32>>(&mut self, value: VALUE) -> &mut Self {
        self.special_info = value.into();
        self
    }
}

fn main() {
    let ch = Channel::default().special_info(42);
    println!("{:?}", ch);
}
```

results in

```
error: borrowed value does not live long enough
  --> <anon>:14:14
14 |>     let ch = Channel::default().special_info(42);
   |>              ^^^^^^^^^^^^^^^^^^ does not live long enough
note: reference must be valid for the block suffix following statement 0 at 14:49...
  --> <anon>:14:50
14 |>     let ch = Channel::default().special_info(42);
   |>                                                  ^
note: ...but borrowed value is only valid for the statement at 14:4
  --> <anon>:14:5
14 |>     let ch = Channel::default().special_info(42);
   |>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: consider using a `let` binding to increase its lifetime
  --> <anon>:14:5
14 |>     let ch = Channel::default().special_info(42);
   |>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

Therefore I would argue that the consuming-pattern should be the preferred choice to support the one-liner-pattern.

CC @killercup

**Comment by duelinmarkers** [comment]
The Builder Pattern post suggests using a builder struct to create an instance of some other type, with a terminal method that creates the instance of the other type, whereas your example uses a struct as its own builder.

**Comment by colin-kiegel** [comment]
@duelinmarkers thank you. Actually that's not entirely true (..or false either). We _do intend_ to have terminal methods on our builder structs, which are supposed to finally "build something". _But_ we leave it to the programmer to implement them with ordinary rust. So yes, I think we do have the same builder pattern in mind, but we don't enforce it (speaking of a macro which auto-generates setter methods to support the builder pattern https://github.com/colin-kiegel/rust-derive-builder/).

EDIT: I didn't include a terminal method in the example above, because it was not relevant there IMO.

**Comment by duelinmarkers** [comment]
But note that the non-consuming builder pattern works fine with one-liners when the terminal "build" method returns a new instance, as is natural when the builder is of a different type than the thing being built. 

As I understand the Builder Pattern, it's essential that the builder is a distinct type from the thing being built. A key responsibility is to protect consumers from getting an incomplete or invalid instance.

**Comment by duelinmarkers** [comment]
Here's your example plus a `build` method, which compiles fine: https://play.rust-lang.org/?gist=368340298b63d884cd75f4870041b8c5&version=stable&backtrace=0

(Apologies for some added but unnecessary lifetime noise and getting rid of the `Into` on the arg. I'm doing this on a tablet where editing is difficult.)

**Comment by colin-kiegel** [comment]
Thx very much, you are right. I guess I misinterpreted the error message. If I remove the let binding and println! in my example it works too. :-)
