### ISSUE TITLE
Link to new fmt-rfcs repo

### ISSUE THREAD

**Issue by johnthagen** [aturon/aturon.github.io#6]
Currently https://aturon.github.io is the number 1 hit on Google for "rust style guide" but it seems to be an old snapshot. Could this instead point to https://github.com/rust-lang-nursery/fmt-rfcs, so that people would be directed to the latest guidelines?

**Comment by aturon** [comment]
Snapshot removed, now info is at https://rust-lang-nursery.github.io/api-guidelines/
