### ISSUE TITLE
stability-dashboard shows up in google

### ISSUE THREAD

**Issue by bluss** [aturon/aturon.github.io#8]
I guess it only happens to the unlucky, but a few find stability-dashboard 's outdated rust docs and don't see that it's out of date or unofficial.

**Comment by esmevane** [comment]
@bluss - Honestly, I just found stability-dashboard last night via a Google search and it was a big eye opener.  [This page in particular](http://aturon.github.io/stability-dashboard/guide-container.html) had stuff in it no other official guide had.  

Why did this one get discontinued?

**Comment by aturon** [comment]
Done.

Guidelines are now here: https://rust-lang-nursery.github.io/api-guidelines/

**Comment by bluss** [comment]
Thanks! :smile:
